### ISSUE TITLE
可以问一下，为什么要重新做身份验证吗？

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#1]
```
我用一个python的twitter库做一个appspot的网站，本地测试的时候
使用你做的代
理，放到appspot上面直接连twitter.com。我发现，如果twitter 
api执行错误的时
候，本地使用代理的时候能正常返回200，并有错误信息的json�
��回值。而放到网上的
时候，twitter 
api如果调用不产生错误，没有问题，而出错的话返回403。我��
�现大
部分情况下，你修改的Authorization和之前是一样的。但是你这�
��改一定有道理的，
能解释一下吗？
```

Original issue reported on code.google.com by `yangwei...@gmail.com` on 22 Sep 2009 at 12:03

**Comment by GoogleCodeExporter** [comment]
```
说实话，其实是没啥用的……
只是之前想过要把OAuth加进来，不过当时对OAuth的没有什么了�
��，代码就先放在那里了。
等这阵子把手头工作忙完，会再改改，把OAuth加进来。
```

Original comment by `rui7905` on 23 Sep 2009 at 12:29

**Comment by GoogleCodeExporter** [comment]
```
我的也出现了这个问题是不是该更新下GTAP？  
怎么更新啊？谢谢
 Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 701, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/hexieci-007/1.344559174403648752/main.py", line 134, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/hexieci-007/1.344559174403648752/main.py", line 95, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/hexieci-007/1.344559174403648752/main.py", line 34, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute
```

Original comment by `my732...@gmail.com` on 6 Nov 2011 at 6:23
