### ISSUE TITLE
上传至GAE出现错误提示

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#119]
```
上传失败，错误提示：

Application: ########; version: 1.
Server: appengine.google.com.
Traceback (most recent call last):
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 69, in <module
>
    run_file(__file__, globals())
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 65, in run_fil
e
    execfile(script_path, globals_)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.p
y", line 3100, in <module>
    main(sys.argv)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.p
y", line 3091, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.p
y", line 2013, in Run
    self.action(self)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.p
y", line 2943, in __call__
    return method()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.p
y", line 2363, in Update
    updatecheck.CheckForUpdates()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.p
y", line 421, in CheckForUpdates
    api_versions=version['api_versions'])
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appengin
e_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "C:\Python27\lib\urllib2.py", line 392, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 410, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 370, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1194, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Program Files\Google\google_appengine\lib\fancy_urllib\fancy_urllib\_
_init__.py", line 342, in do_open
    req)
  File "C:\Python27\lib\urllib2.py", line 1155, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "C:\Python27\lib\httplib.py", line 941, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 975, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 937, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 797, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 759, in send
    self.connect()
  File "C:\Program Files\Google\google_appengine\lib\fancy_urllib\fancy_urllib\_
_init__.py", line 158, in connect
    'hostname mismatch')
fancy_urllib.InvalidCertificateException: Host appengine.google.com returned an
invalid certificate (hostname mismatch): {'notAfter': 'Dec 18 23:59:59 2011 GMT'
, 'subject': ((('countryName', u'US'),), (('stateOrProvinceName', u'California')
,), (('localityName', u'Mountain View'),), (('organizationName', u'Google Inc'),
), (('commonName', u'www.google.com'),))}
To learn more, see http://code.google.com/appengine/kb/general.html#rpcssl

说主机名错误，经检查userid无误。求解
```

Original issue reported on code.google.com by `vince0...@gmail.com` on 6 Dec 2010 at 7:07

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
已解决，是hosts里有一行已失效的AppEngine地址，删掉后排除。
感谢SAPikachu
```

Original comment by `vince0...@gmail.com` on 7 Dec 2010 at 4:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `rui7905` on 8 Dec 2010 at 1:58
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
我也遇到这个问题    请问怎么解决的  thx in advance
```

Original comment by `ZhangHighly` on 7 Apr 2012 at 10:01
