### ISSUE TITLE
第二次在twitter上oauth后一直报Incorrect padding 问题。

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#122]
```

12-12 11:46PM 31.909 /account/verify_credentials.json 500 62ms 0cpu_ms 0kb 
TwitBirdFree/2.7.3 CFNetwork/485.12.7 Darwin/10.4.0,gzip(gfe)
135.11.3.4 - - [12/Dec/2010:23:46:31 -0800] "GET 
/account/verify_credentials.json HTTP/1.1" 500 941 - "TwitBirdFree/2.7.3 
CFNetwork/485.12.7 Darwin/10.4.0,gzip(gfe)" "twitapis.appspot.com" ms=63 
cpu_ms=0 api_cpu_ms=0 cpm_usd=0.000166
E 12-12 11:46PM 31.913
Incorrect padding
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 515, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/twitapis/2.346783254669545103/main.py", line 153, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/twitapis/2.346783254669545103/main.py", line 115, in do_proxy
    username, password = self.parse_auth_header(self.request.headers)
  File "/base/data/home/apps/twitapis/2.346783254669545103/main.py", line 98, in parse_auth_header
    user_pass_parts = base64.b64decode(auth_parts[1]).split(':')
  File "/base/python_runtime/python_dist/lib/python2.5/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```

Original issue reported on code.google.com by `sunjiali...@gmail.com` on 13 Dec 2010 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
把API由appspot.com改成appspot.com/api/后，就可以使用了。不过有��
�还是报这个错误。看了twitbird的blog后，发现可能是 
TwitBirdFree/2.7.3 bug。
12-14 04:10AM 21.968 /api/oauth/access_token 500 640ms 23cpu_ms 0kb 
TwitBirdFree/2.7.3 CFNetwork/485.12.7 Darwin/10.4.0,gzip(gfe)
60.20.145.94 - - [14/Dec/2010:04:10:22 -0800] "POST /api/oauth/access_token 
HTTP/1.1" 500 944 - "TwitBirdFree/2.7.3 CFNetwork/485.12.7 
Darwin/10.4.0,gzip(gfe)" "twitapis.appspot.com" ms=640 cpu_ms=23 api_cpu_ms=0 
cpm_usd=0.000824 pending_ms=611
E 12-14 04:10AM 22.582
Incorrect padding
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 517, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/twitapis/1.346884307589822251/main.py", line 150, in post
    self.do_proxy('POST')
  File "/base/data/home/apps/twitapis/1.346884307589822251/main.py", line 115, in do_proxy
    username, password = self.parse_auth_header(self.request.headers)
  File "/base/data/home/apps/twitapis/1.346884307589822251/main.py", line 98, in parse_auth_header
    user_pass_parts = base64.b64decode(auth_parts[1]).split(':')
  File "/base/python_runtime/python_dist/lib/python2.5/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```

Original comment by `sunjiali...@gmail.com` on 14 Dec 2010 at 1:23
