### ISSUE TITLE
gtap支持twitter官方的iOS版客户端吗？

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#123]
```
官方的iPhone app可以自定义API。貌似gtap不支持。
```

Original issue reported on code.google.com by `sunjiali...@gmail.com` on 13 Dec 2010 at 7:53

**Comment by GoogleCodeExporter** [comment]
```
App error log
12-13 05:45AM 18.741 /api/1/oauth/access_token 500 5ms 0cpu_ms 0kb 
Twitter/3.2.1 CFNetwork/485.12.7 Darwin/10.4.0,gzip(gfe)
113.227.212.252 - - [13/Dec/2010:05:45:18 -0800] "POST 
/api/1/oauth/access_token HTTP/1.1" 500 797 - "Twitter/3.2.1 CFNetwork/485.12.7 
Darwin/10.4.0,gzip(gfe)" "twitapis.appspot.com" ms=6 cpu_ms=0 api_cpu_ms=0 
cpm_usd=0.000145
E 12-13 05:45AM 18.743
list index out of range
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 517, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/twitapis/1.346884307589822251/main.py", line 150, in post
    self.do_proxy('POST')
  File "/base/data/home/apps/twitapis/1.346884307589822251/main.py", line 115, in do_proxy
    username, password = self.parse_auth_header(self.request.headers)
  File "/base/data/home/apps/twitapis/1.346884307589822251/main.py", line 100, in parse_auth_header
    password = user_pass_parts[1]
IndexError: list index out of range
```

Original comment by `sunjiali...@gmail.com` on 14 Dec 2010 at 1:24
