### ISSUE TITLE
修改api key时遇到的问题

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#129]
```
你好，按照你的方法在gae上搭建了一个api，oauth没有问题。但
是在修改api密码时，页面会提示Can not find user from db, or invalid 
old_key.检查大小写无误。到GAE后台发现oauth回来修改密码的话D
atastore 
Viewer里面会多一条记录。全部删掉之后重新oauth，成功，立刻
修改密码，成功，立刻再次修改密码，就失败了。同样提示Ca
n not find user from db, or invalid 
old_key.最终搜索发现貌似是twitter帐户用户名大小写的问题，��
�似账号内不能有大写字母。否则就会出现Can not find user from 
db, or invalid 
old_key.经官网修改帐号名全为小写的时候，此问题得以解决。
恳请修复此bug，谢谢。
```

Original issue reported on code.google.com by `198...@gmail.com` on 10 Jan 2011 at 5:24

**Comment by GoogleCodeExporter** [comment]
```
好的，我来查查看
```

Original comment by `rui7905` on 13 Jan 2011 at 3:00
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
试了一下，确实只有含有大小写的用户名会提示

Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 517, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/mikegtap2/1.348098959849770255/main.py", line 219, in post
    user_access_token, user_access_secret  = client.get_access_from_db(screen_name, old_key)
  File "/base/data/home/apps/mikegtap2/1.348098959849770255/oauth.py", line 206, in get_access_from_db
    result.decrypt(password)
  File "/base/data/home/apps/mikegtap2/1.348098959849770255/oauth.py", line 56, in decrypt
    self.token  = DecodeAES(self.create_aes(self_key), self.token)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 541, in __set__
    value = self.validate(value)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2435, in validate
    raise BadValueError('Property %s is not multi-line' % self.name)
BadValueError: Property token is not multi-line


只要ScreenName含有大小写混合的，会提示上面的信息，使用的�
��SVN r73的gtap
```

Original comment by `minamima...@gmail.com` on 5 Feb 2011 at 5:11

**Comment by GoogleCodeExporter** [comment]
```
我的含有大小写，还有下划线都没问题。一切安好。
用的0.4版。
```

Original comment by `xmuschna...@gmail.com` on 26 Oct 2011 at 4:17
