### ISSUE TITLE
都有哪些客户端可以使用gtap

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#132]
```
出了很多莫名其妙的事情，但终于还是假设成功了，也在twitt
er的帐号里allow了。访问xxx.appspot.com显示running。但是我在桌面
端使用的TweetDeck，Chrome上的FaWave，Chrowety都不成功。怎么判断
api 
proxy已经开始运作了？或者大家有没有确定可用的客户端推荐
一下？非常感谢。
```

Original issue reported on code.google.com by `spinac...@gmail.com` on 28 Jan 2011 at 9:35

**Comment by GoogleCodeExporter** [comment]
```
好吧，现在的问题是不能change key，开着openvpn的情况下，
出错代码如下：
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 517, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/folding-ladder/b1.347946795335692676/main.py", line 223, in post
    user_access_token, user_access_secret  = client.get_access_from_db(screen_name, old_key)
  File "/base/data/home/apps/folding-ladder/b1.347946795335692676/oauth.py", line 206, in get_access_from_db
    result.decrypt(password)
  File "/base/data/home/apps/folding-ladder/b1.347946795335692676/oauth.py", line 56, in decrypt
    self.token  = DecodeAES(self.create_aes(self_key), self.token)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 541, in __set__
    value = self.validate(value)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2435, in validate
    raise BadValueError('Property %s is not multi-line' % self.name)
BadValueError: Property token is not multi-line
```

Original comment by `spinac...@gmail.com` on 28 Jan 2011 at 10:28

**Comment by GoogleCodeExporter** [comment]
```
同上，不能change key
```

Original comment by `minamima...@gmail.com` on 5 Feb 2011 at 5:04
