### ISSUE TITLE
重新上传GTAP后出现问题

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#142]
```
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 634, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/vnlineapi/1.349355084367894009/main.py", line 136, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/vnlineapi/1.349355084367894009/main.py", line 96, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/vnlineapi/1.349355084367894009/main.py", line 35, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute

本来不更新运行很正常的。我重新上传，更新后就出现这样��
�问题了。新建应用上传同样也是这个问题，但本地调试却正�
��。这是什么原因造成的？
```

Original issue reported on code.google.com by `xiuqua...@gmail.com` on 30 Mar 2011 at 3:06

**Comment by GoogleCodeExporter** [comment]
```
我也是这个问题....
```

Original comment by `dengjing...@gmail.com` on 30 Mar 2011 at 5:12

**Comment by GoogleCodeExporter** [comment]
```
我上传更新了这个app。打开虽然有问题，但是还是可以用。��
�个问题可能是GAE的问题。
```

Original comment by `xiuqua...@gmail.com` on 31 Mar 2011 at 5:49

**Comment by GoogleCodeExporter** [comment]
```
没有更新，但是发现今天出现了问题....
```

Original comment by `mjmars...@gmail.com` on 31 Mar 2011 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
我也是这个问题
```

Original comment by `hlp...@gmail.com` on 2 Apr 2011 at 4:33

**Comment by GoogleCodeExporter** [comment]
```
我也是……
```

Original comment by `imccy...@gmail.com` on 2 Apr 2011 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
等待问题解决……
```

Original comment by `acm...@gmail.com` on 5 Apr 2011 at 2:34

**Comment by GoogleCodeExporter** [comment]
Original comment by `rui7905` on 6 Apr 2011 at 4:41
- Changed state: **Fixed**
