### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#143]
```
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 634, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/rui7905/1.347621880265485487/main.py", line 143, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/rui7905/1.347621880265485487/main.py", line 103, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/rui7905/1.347621880265485487/main.py", line 45, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute

现在部署后出现这样的问题，请问该如何解决？
```

Original issue reported on code.google.com by `m...@beta4better.me` on 30 Mar 2011 at 3:01

**Comment by GoogleCodeExporter** [comment]
```
重装后我也出现这个问题，但我的是以前部署好的，现在还��
�运行
```

Original comment by `jiaquan...@gmail.com` on 31 Mar 2011 at 12:04

**Comment by GoogleCodeExporter** [comment]
```
同出现这样的问题
原先使用的api页面访问也是这个错误，但是之前在用的还可��
�继续用
新上传的api也是这个错误，但是这样就没法注册新的应用了
```

Original comment by `brokl...@gmail.com` on 1 Apr 2011 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
新注册的应用也会出现同样问题。这个问题应该是gae的问题��
�不关源码的事。我重新设置了，依然没有变更。应该是GAE现�
��部署不了GTAP应用。如果原先有建立过的话，还是可以用的��
�
```

Original comment by `xiuqua...@gmail.com` on 1 Apr 2011 at 3:08

**Comment by GoogleCodeExporter** [comment]
```
要如何解决呢？
```

Original comment by `imccy...@gmail.com` on 2 Apr 2011 at 10:10

**Comment by GoogleCodeExporter** [comment]
```
等解决办法～
```

Original comment by `rabbitzhang52` on 3 Apr 2011 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
搞了一个下午，总是出现这个问题。等解决啊.......
```

Original comment by `tzl3...@gmail.com` on 3 Apr 2011 at 9:37

**Comment by GoogleCodeExporter** [comment]
```
我也是……
```

Original comment by `acm...@gmail.com` on 5 Apr 2011 at 2:29

**Comment by GoogleCodeExporter** [comment]
```
等待....
```

Original comment by `fount.yan@gmail.com` on 5 Apr 2011 at 3:06

**Comment by GoogleCodeExporter** [comment]
```
最近gtap也出现此错误。。

Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 634, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/fanqiangsh/1.345472294548436501/main.py", line 136, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/fanqiangsh/1.345472294548436501/main.py", line 96, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/fanqiangsh/1.345472294548436501/main.py", line 35, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute
```

Original comment by `zengh...@gmail.com` on 5 Apr 2011 at 1:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `rui7905` on 6 Apr 2011 at 4:28
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r74.
```

Original comment by `rui7905` on 6 Apr 2011 at 4:32
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
我也是
```

Original comment by `ljj1...@gmail.com` on 30 Apr 2011 at 5:59

**Comment by GoogleCodeExporter** [comment]
```
我调试后认为产生这个问题的原因是twitter新版界面返回的内�
��里有location转向
<script type="text/javascript">
//<![CDATA[
window.location.replace('/#!/twitter_username_here');
//]]>
</script>

我的patch:

                data_ctnt = data.content
                logging.debug( "data = (%s)" % data_ctnt )
                if "window.location.replace('/#!" in data_ctnt:
                    logging.debug( "replacing...." )
                    data_ctnt = data_ctnt.replace( "window.location.replace('/#!", "//window.location.replace('/#!" )

                self.response.out.write(data_ctnt)

即注释掉它，我用下来没这问题了。

供大家参考。
```

Original comment by `binjo...@gmail.com` on 3 May 2011 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
楼上的兄弟可以详细点么，看不懂呢。
```

Original comment by `yhl10...@gmail.com` on 9 May 2011 at 7:44

**Comment by GoogleCodeExporter** [comment]
```
rui7905在11楼给出的版本已经可以解决了~验证通过
```

Original comment by `gclover1...@gmail.com` on 23 May 2011 at 5:41

**Comment by GoogleCodeExporter** [comment]
```
11楼的版本，不能 change key ，也就不能使用
```

Original comment by `gone.w...@gmail.com` on 29 Jun 2011 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r75.
```

Original comment by `rui7905` on 6 Aug 2011 at 6:25
