### ISSUE TITLE
不能用啊！

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#144]
```
在客户端，断断续续能刷出TL，但是不能发推。
在浏览器打开app，显示错误如下：
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 634, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/XXXXXX/1.349450173667544551/main.py", line 136, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/XXXXXX/1.349450173667544551/main.py", line 96, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/XXXXXX/1.349450173667544551/main.py", line 35, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute


```

Original issue reported on code.google.com by `kevin.li...@gmail.com` on 3 Apr 2011 at 4:10

**Comment by GoogleCodeExporter** [comment]
```
同样的问题+1；
搞不清楚是什么原因。之前还是好好的没有这个问题提示的��
�
```

Original comment by `elsonk...@gmail.com` on 11 Apr 2011 at 6:17

**Comment by GoogleCodeExporter** [comment]
```
me too 
,之前一切正常，最近用浏览器打开提示错误，但是api能正常�
��用
```

Original comment by `andrea....@gmail.com` on 10 May 2011 at 2:57
