### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#147]
```
上传最新的0.4.1版本后，遇到如下错误：



Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 634, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/yayublogs/1.349991535511926125/main.py", line 136, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/yayublogs/1.349991535511926125/main.py", line 96, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/yayublogs/1.349991535511926125/main.py", line 35, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute
```

Original issue reported on code.google.com by `yuyang...@gmail.com` on 28 Apr 2011 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
我的也一样 怎么办啊
```

Original comment by `a809757...@gmail.com` on 6 Jun 2011 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
反正GAE已经被彻底墙掉了，修好估计也没啥意义了。。。
```

Original comment by `yuyang...@gmail.com` on 9 Jun 2011 at 1:31
