### ISSUE TITLE
上传几次后打开页面出来的都是Traceback (most recent call last)什么什么的TAT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#149]
```
每次上传后都这样……就改几个地方而已应该不会出错的啊��
�…
我什么都不懂谁来帮帮我啊TAT


出来的就是这样的东西……


Traceback (most recent call last):
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 3858, in _HandleRequest
    self._Dispatch(dispatcher, self.rfile, outfile, env_dict)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 3792, in _Dispatch
    base_env_dict=env_dict)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 580, in Dispatch
    base_env_dict=base_env_dict)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2918, in Dispatch
    self._module_dict)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2822, in ExecuteCGI
    reset_modules = exec_script(handler_path, cgi_path, hook)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2702, in ExecuteOrImportScript
    exec module_code in script_module.__dict__
  File "C:\Users\lenovo\Desktop\gtap-0.4\main.py", line 10, in <module>
    import oauth
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 1440, in Decorate
    return func(self, *args, **kwargs)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2360, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 1440, in Decorate
    return func(self, *args, **kwargs)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2249, in FindAndLoadModule
    description)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 1440, in Decorate
    return func(self, *args, **kwargs)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\dev_appserver.py", line 2194, in LoadModuleRestricted
    description)
  File "C:\Users\lenovo\Desktop\gtap-0.4\oauth.py", line 14, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher


求解……
```

Original issue reported on code.google.com by `yukot...@gmail.com` on 7 May 2011 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
Go to the link below,download and install PyCrypto binaries for Windows.

http://www.voidspace.org.uk/python/modules.shtml#pycrypto

```

Original comment by `keket...@gmail.com` on 17 May 2011 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
这个链接～
已经解决～
http://code.google.com/p/gtap/source/detail?r=74#
```

Original comment by `REALISW...@gmail.com` on 29 May 2011 at 7:32
