### ISSUE TITLE
无法使用了

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#152]
```
这是报错信息
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 700, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/gtapserver1/1.344522571150578422/main.py", line 136, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/gtapserver1/1.344522571150578422/main.py", line 96, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/gtapserver1/1.344522571150578422/main.py", line 35, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute
```

Original issue reported on code.google.com by `yaf...@gmail.com` on 11 Jun 2011 at 2:55

**Comment by GoogleCodeExporter** [comment]
```
已经解决
http://code.google.com/p/gtap/source/detail?r=74
```

Original comment by `yaf...@gmail.com` on 11 Jun 2011 at 3:04
