### ISSUE TITLE
error on home

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#154]
```
What steps will reproduce the problem?
1. deploy gtap-0.4.1 on GAE application as documented
2. open the homepage for the application in a browser 
3. there displays python traceback message on the page

What is the expected output? What do you see instead?
display the oauth page or others

I see: 
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 700, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/phptwit/1.344208310362664609/main.py", line 134, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/phptwit/1.344208310362664609/main.py", line 95, in do_proxy
    return success_output(self, gtap_message )
  File "/base/data/home/apps/phptwit/1.344208310362664609/main.py", line 34, in success_output
    handler.response.status = '200 OK'
AttributeError: can't set attribute


What version of the product are you using? On what operating system?
gtap-0.4.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `Leiping....@gmail.com` on 14 Jun 2011 at 3:46

**Comment by GoogleCodeExporter** [comment]
```
The same error ...
r74 has been used ...
```

Original comment by `liu...@gmail.com` on 18 Jun 2011 at 3:04

**Comment by GoogleCodeExporter** [comment]
```
Go to https://appengine.google.com/ ，click your app id on the left.Find the 
link "Versions"on the left.Set the new version as default. OK!!... 
```

Original comment by `liugehuan@gmail.com` on 18 Jun 2011 at 3:54
