### ISSUE TITLE
无法修改 key

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#157]
```
已修改 r74. 认证授权后, 若修改默认 key 将出现下列提示, 
并无法成功修改 key:

Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/username/1.351295640984524430/main.py", line 223, in post
    user_access_token, user_access_secret  = client.get_access_from_db(screen_name, old_key)
  File "/base/data/home/apps/username/1.351295640984524430/oauth.py", line 206, in get_access_from_db
    result.decrypt(password)
  File "/base/data/home/apps/username/1.351295640984524430/oauth.py", line 56, in decrypt
    self.token  = DecodeAES(self.create_aes(self_key), self.token)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 594, in __set__
    value = self.validate(value)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2668, in validate
    raise BadValueError('Property %s is not multi-line' % self.name)
BadValueError: Property token is not multi-line
```

Original issue reported on code.google.com by `Akcipit...@gmail.com` on 21 Jun 2011 at 6:12

**Comment by GoogleCodeExporter** [comment]
```
多试几次就可以了
```

Original comment by `wallace....@gmail.com` on 1 Jul 2011 at 6:41
