### ISSUE TITLE
0.4.2 couldn't work on iOS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#164]
```
ubuntu lucid, python2.65, gtap4.2, crack Twitbird Pro, jailbreak iOS.

1. Upload & deploy gae successfully.

2. Bind domain XXX.appspot.com with usable Google IP. 

3. Pass Oauth through VPN, iPad app works fine. 
Switch to WiFi, set api proxy in "http://XXX.appspot.com" OR 
"http://XXX.appspot.com/api/1/" format according to tutorial, no matter with or 
without SSL, both could not fetch twitter feeds through this API.

Questions:
What's wrong with the process?


# Previous logs as below

1.
      2011-10-02 16:07:44.660 /direct_messages/sent.json?count=200&since_id=-1 500 285ms 0cpu_ms 0kb TwitBirdPro/2.8 CFNetwork/485.13.9 Darwin/11.0.0
      See details

      113.64.8.192 - - [02/Oct/2011:16:07:44 -0700] "GET /direct_messages/sent.json?count=200&since_id=-1 HTTP/1.1" 500 941 - "TwitBirdPro/2.8 CFNetwork/485.13.9 Darwin/11.0.0" "XXX.appspot.com" ms=285 cpu_ms=0 api_cpu_ms=0 cpm_usd=0.000171 pending_ms=258 instance=00c61b117c3fe49e61581ee6e32da04c5bbc

2.
      E 2011-10-02 16:07:44.658

      Incorrect padding
      Traceback (most recent call last):
        File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 701, in __call__
          handler.get(*groups)
        File "/base/data/home/apps/s~XXX/1.353687622782677936/main.py", line 131, in get
          self.do_proxy('GET')
        File "/base/data/home/apps/s~XXX/1.353687622782677936/main.py", line 93, in do_proxy
          username, password = self.parse_auth_header(self.request.headers)
        File "/base/data/home/apps/s~XXX/1.353687622782677936/main.py", line 76, in parse_auth_header
          user_pass_parts = base64.b64decode(auth_parts[1]).split(':')
        File "/base/python_runtime/python_dist/lib/python2.5/base64.py", line 76, in b64decode
          raise TypeError(msg)
      TypeError: Incorrect padding
```

Original issue reported on code.google.com by `christie...@gmail.com` on 3 Oct 2011 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
IOS上根本用不了GTAP，有没有什么解决方法啊
```

Original comment by `jacksu...@gmail.com` on 21 Jul 2012 at 2:11

**Comment by GoogleCodeExporter** [comment]
```
no other solution yet. buy one instead.
```

Original comment by `christie...@gmail.com` on 21 Jul 2012 at 4:30
