### ISSUE TITLE
似乎不稳定

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#18]
```
用这个版本oauth的，但是GAE上似乎errors很多，实际用客户端的
时候也不太稳定
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Original issue reported on code.google.com by `kally11...@gmail.com` on 2 Jun 2010 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
说明一下是这个版本gtap-oauth-rev6-2.7z
```

Original comment by `kally11...@gmail.com` on 2 Jun 2010 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
我倒是没出现过这种错误，基本上都是DownloadError。那个错误�
��在访问哪些url的时候出现的呢？
```

Original comment by `SAPika...@gmail.com` on 3 Jun 2010 at 12:35

**Comment by GoogleCodeExporter** [comment]
```
dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File 
"/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__
.py", 
line 511, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/gtap应用地址/1.342357412098779893/oauth.py", line 534, 
in get
    self.handle(service,action)
  File "/base/data/home/apps/gtap应用地址/1.342357412098779893/oauth.py", line 549, 
in handle
    self.response.out.write(getattr(client, action)())
  File "/base/data/home/apps/gtap应用地址/1.342357412098779893/oauth.py", line 303, 
in login
    return self.get_request_token()
  File "/base/data/home/apps/gtap应用地址/1.342357412098779893/oauth.py", line 319, 
in get_request_token
    **dict(token.split('=') for token in token_info.split('&'))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
实际使用的时候就是掉线蛮多的
```

Original comment by `kally11...@gmail.com` on 3 Jun 2010 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
看看控制面板log里面显示的是什么地址？
```

Original comment by `SAPika...@gmail.com` on 3 Jun 2010 at 2:33

**Comment by GoogleCodeExporter** [comment]
```
06-01 01:31AM 18.376 /oauth/twitter/login 500 481ms 19cpu_ms 0kb Mozilla/5.0 
(Windows; 
U; Windows NT 6.1; en-US) AppleWebKit/534.0 (KHTML, like Gecko) 
Chrome/6.0.414.0 
Safari/534.0,gzip(gfe)
114.229.250.93 - - [01/Jun/2010:01:31:18 -0700] "GET /oauth/twitter/login 
HTTP/1.1" 500 
534 - "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.0 
(KHTML, like 
Gecko) Chrome/6.0.414.0 Safari/534.0,gzip(gfe)"
这个吗？
```

Original comment by `kally11...@gmail.com` on 3 Jun 2010 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
 /gtap_oauth/kally11112/lists/subscriptions.json?好像这个显示最多

```

Original comment by `kally11...@gmail.com` on 3 Jun 2010 at 2:44

Attachments:
- [未命名.jpg](https://storage.googleapis.com/google-code-attachments/gtap/issue-18/comment-6/未命名.jpg)

**Comment by GoogleCodeExporter** [comment]
```
list有问题的话，好像之前也有人碰到过，试试重新login一次��
�不会有改善？
```

Original comment by `SAPika...@gmail.com` on 3 Jun 2010 at 3:27

**Comment by GoogleCodeExporter** [comment]
```
好像解决了，因为我没有把OAuth的key和secret填入oauth.py而只填�
��了oaouth_config.py中，这
两个应该都要填吧，建议在说明文档中第二行注明，上面只��
�了填在oauth_config.py中
```

Original comment by `kally11...@gmail.com` on 3 Jun 2010 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
哦，补充下，如果限制用户的话，这两个文件中的相关地方��
�要都填吧，这个说明文档里也没
```

Original comment by `kally11...@gmail.com` on 3 Jun 2010 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
呃。。。只需要填入oauth_config.py的啊，oauth.py是不需要修改的
。你修改之后有重新注册过
api密码么？
```

Original comment by `SAPika...@gmail.com` on 3 Jun 2010 at 9:44

**Comment by GoogleCodeExporter** [comment]
```
没有重新注册过，只是我填了之后，就没有errors了，很神奇��
�
```

Original comment by `kally11...@gmail.com` on 3 Jun 2010 at 1:23

**Comment by GoogleCodeExporter** [comment]
```
好奇怪。。。
```

Original comment by `SAPika...@gmail.com` on 4 Jun 2010 at 7:39

**Comment by GoogleCodeExporter** [comment]
```
请问具体应该把consumer 
key/secret填在oauth.py的哪个地方？打开oauth.py之后里面含有consum
er key字样的地方还是有几处呢。
```

Original comment by `zjs...@gmail.com` on 8 Mar 2011 at 2:58
