### ISSUE TITLE
无法上传

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#31]
```
用的是oauth-dev，无法上传。code：Traceback (most recent call last):
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 1535, in DoUpload
    missing_files = self.Begin()
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 1305, in Begin
    version=self.version, payload=self.config.ToYAML())
  File "/home/zhngtianshu/GAE/google/appengine/tools/appengine_rpc.py", line 346, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/home/zhngtianshu/GAE/google/appengine/tools/https_wrapper.py", line 136, in https_open
    return self.do_open(http_class_wrapper, req)
  File "/usr/lib/python2.6/urllib2.py", line 1136, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "appcfg.py", line 68, in <module>
    run_file(__file__, globals())
  File "appcfg.py", line 64, in run_file
    execfile(script_path, globals_)
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 2757, in <module>
    main(sys.argv)
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 2748, in main
    result = AppCfgApp(argv).Run()
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 1763, in Run
    self.action(self)
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 2619, in __call__
    return method()
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 2070, in Update
    lambda path: open(os.path.join(basepath, path), 'rb'))
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 1535, in DoUpload
    missing_files = self.Begin()
  File "/home/zhngtianshu/GAE/google/appengine/tools/appcfg.py", line 1305, in Begin
    version=self.version, payload=self.config.ToYAML())
  File "/home/zhngtianshu/GAE/google/appengine/tools/appengine_rpc.py", line 346, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/home/zhngtianshu/GAE/google/appengine/tools/https_wrapper.py", line 136, in https_open
    return self.do_open(http_class_wrapper, req)
  File "/usr/lib/python2.6/urllib2.py", line 1136, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

Original issue reported on code.google.com by `nanshan...@gmail.com` on 14 Jun 2010 at 1:28

**Comment by GoogleCodeExporter** [comment]
```
GAE上传已经被墙，要挂上代理。。。
```

Original comment by `SAPika...@gmail.com` on 15 Jun 2010 at 1:53

**Comment by GoogleCodeExporter** [comment]
```
发现解决方法了：appcfg.py --insecure 上传
```

Original comment by `nanshan...@gmail.com` on 18 Jun 2010 at 4:30
