### ISSUE TITLE
新版本中如何修改KEY

### ISSUE THREAD

**Issue by GoogleCodeExporter** [YJSoft/gtap#44]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `jrk1987@gmail.com` on 23 Jul 2010 at 3:52

**Comment by GoogleCodeExporter** [comment]
```
http://xxx.appspot.com/oauth/change
```

Original comment by `rui7905` on 26 Jul 2010 at 9:54
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
用上0.4.1版，验证后更改api 
key时出现以下错误提示，该如何解决？

Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 513, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/jetchung-gtap/4.344832128166082991/main.py", line 223, in post
    user_access_token, user_access_secret  = client.get_access_from_db(screen_name, old_key)
  File "/base/data/home/apps/jetchung-gtap/4.344832128166082991/oauth.py", line 206, in get_access_from_db
    result.decrypt(password)
  File "/base/data/home/apps/jetchung-gtap/4.344832128166082991/oauth.py", line 58, in decrypt
    self.secret = DecodeAES(self.create_aes(self_key), self.secret)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 542, in __set__
    value = self.validate(value)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2453, in validate
    raise BadValueError('Property %s is not multi-line' % self.name)
BadValueError: Property secret is not multi-line
```

Original comment by `gengjiec...@gmail.com` on 16 Sep 2010 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
同问。
```

Original comment by `zxc262...@gmail.com` on 26 Nov 2010 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
恩，的确是个BUG…… 谢谢你的log
```

Original comment by `rui7905` on 27 Nov 2010 at 6:01
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
这个Bug解了么？我用最新的0.4.2也有同样的问题。
Property secret is not multi-line
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 701, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/s~fadefy/1.356789677338968868/main.py", line 131, in get
    self.do_proxy('GET')
  File "/base/data/home/apps/s~fadefy/1.356789677338968868/main.py", line 104, in do_proxy
    user_access_token, user_access_secret  = client.get_access_from_db(username, password)
  File "/base/data/home/apps/s~fadefy/1.356789677338968868/oauth.py", line 206, in get_access_from_db
    result.decrypt(password)
  File "/base/data/home/apps/s~fadefy/1.356789677338968868/oauth.py", line 58, in decrypt
    self.secret = DecodeAES(self.create_aes(self_key), self.secret)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 613, in __set__
    value = self.validate(value)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2821, in validate
    raise BadValueError('Property %s is not multi-line' % self.name)
BadValueError: Property secret is not multi-line
```

Original comment by `fad...@gmail.com` on 15 May 2012 at 11:58
